### ISSUE TITLE
준홍스 숙제

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#1]
1) 깃헙 몇개 트라이 commit push 몇개 트라이
2) requirement를 다큐멘트 상세할수록 좋음
3) 디자인 생각해보기. 
4) 구글에서 tutorial 찾아보기 idea brainstorm 예를 들자면
- 데이타 싸이언스와 그래프 앱을 쓸수 있는 다른 기능들
- 연구나 일에 사용도가 높을 수록 좋음
- 큰 프로젝트 아이디어

**Comment by jsong0521** [comment]
Junhong Song is inviting you to a scheduled Zoom meeting.

Topic: Github과 이것저것
Time: Apr 13, 2020 06:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://us04web.zoom.us/j/78181133299?pwd=YlVwTXhqTElzVXArTTlpemFWSDFCdz09

Meeting ID: 781 8113 3299
Password: 4tuQi8

2020년 4월 13일 (월) 오후 3:46, cw-infinite <notifications@github.com>님이 작성:

**Comment by jsong0521** [comment]
읽을자료

https://jakevdp.github.io/PythonDataScienceHandbook/04.12-three-dimensional-plotting.html
https://matplotlib.org/mpl_toolkits/mplot3d/tutorial.html
https://matplotlib.org/gallery/mplot3d/rotate_axes3d.html

**Comment by jsong0521** [comment]
Matplotlib 우선 배워놨으니 위키에 정리해서 추가
위키페이지에 대해 질문하기
