### ISSUE TITLE
"F(x) = [input]" implementation for multiple 

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#10]
- Multiple lines supported
- buttons for different functions (CRUD):
  - add 
  - delete
  - edit
  - color
- Basic Semantic UI design

**Comment by jsong0521** [comment]
Minor suggestion:
앞으로 용어를 Function보다는 Equation으로 통일하는게 좋을 것 같음.
마찬가지로 Dependent Variable 역시 f(x)보다는 y로 명명하는게 좋음.
통계에서는 구구절절한 이유때문에 f(x)보다는 y를 주로 사용하기 때문

**Comment by jsong0521** [comment]
차트 하나에 그래프를 여러개 그릴 수 있게 된다면, 각 그래프마다 아래의 옵션들을 선택할 수 있는 기능이 추가되어야 할 것 같음:

Label

Line Option
- Color
- Style
- Width (이건 있어도 되고 없어도 되는데 라인의 굵기를 뜻함)

**Comment by cw-infinite** [comment]
as of v0.3 only [y=x] functionality was addedd.

Line Option
- Color 
- Style
- Width

 (이건 있어도 되고 없어도 되는데 라인의 굵기를 뜻함)
more on future prototypes

**Comment by cw-infinite** [comment]
https://github.com/cw-infinite/graphicachu/issues/42 Color 끝. 다음은 ... Width
