### ISSUE TITLE
금융 스터디

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#105]
새로운 프로젝트 1/7
숙제
Financial statement 공부해오기
@jsong0521 : JMIA
@cw-infinite : DAL

Rating에 중요할꺼같은 variable 공부해오기 3개

Due date : Jan 21st 2021

**Comment by cw-infinite** [comment]
Applied Statement 기간은 2020년도. 코비드를 중심으로 혹은 그 시기 performance

**Comment by jsong0521** [comment]
http://highered.mheducation.com/sites/0073324833/student_view0/ebook/chapter1/chbody1/the_four_basic_financial_statements__an_overview.html

리소스

**Comment by jsong0521** [comment]
이 프로젝트를 터미네이트하고 다른걸로 무브온 해야할 이유가 생김..
자세한건 내일
