### ISSUE TITLE
High level feature designs requirements on "Number Pad"

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#12]
사용자/통계충 시점에서의 usability 면에서 있으면 편한 기능들/자주쓰는기능들
만약 기본 universal한 공식이 있어서 값만 넣으면 되는 공식들도 reference 해주면 좋을꺼같음

1. 일단 형이 평상시 일에서 쓸수 있는 기능들을 중점으로 생각을 해보자

있으면 좋을꺼같을 기능들
- 키보드 keypad 사용가능.
- pre-built f(x)
- 다른 그래프 사이트 기능들 벤치마크

UI 적인 면에서도 high level 버튼 배치, 버튼의 행동명령들 (구체적일수록 좋음 )의 방향을 제시해주는것도 좋음

**Comment by jsong0521** [comment]
내일 미팅때 팔로업 필요함

**Comment by jsong0521** [comment]
대부분의 math expression이 지원되니 굳이 number pad가 필요하지 않을 수 도 있을 것 같다는 생각이 듬

대신 옆에 "?"등을 누르면 Aide 팝업이 떠서 지원되는 expression 종류를 제안해주는게 어떨지?

**Comment by cw-infinite** [comment]
그것도 아주 좋은 생각임. 그렇게 팝업을 Tooltip 이라고 하는데 
number pad는 나중에 디테일한 공식을 쓰게되면(?) 필요할 수 도 있어서 버젼 1.0에는 빼고 그 후속작들에서 생각해보는걸로?

**Comment by jsong0521** [comment]
굿!
그러면 Tooltip으로 쓸 지원되는 math function을 만들기 시작하겠음

**Comment by cw-infinite** [comment]
5/14 meeting review
