### ISSUE TITLE
디자인 제출

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#13]
Prototype .2 디자인 제출

**Comment by cw-infinite** [comment]
디자인은 high level로 방향성제시가 더 좋을꺼같음
방향성을 제시해주면 내가 hot fix로 여러가지 제시안을 줄 수 있음 
보통 내 recommendation에서 형이 고르거나 내가 추천하는걸로 가는 쪽으로 하자

**Comment by cw-infinite** [comment]
디자인에 **어떤 그래프 옵션**이 더 들어갔으면 하는지 알 수 있을까.

예를 들자면 **점 그래프, 라인 그래프, 바 그래프**, 여러가지 바꿀수 있는 그래프 들을 
제시해 주고 내가 거기서 실행 가능한것과 안되면 alternatives를 다시 제시해줄께

**Comment by jsong0521** [comment]
이렇게 말이오? *Sold -> Solid

![Line Style](https://user-images.githubusercontent.com/63434481/80280757-11eaa300-86d4-11ea-9e6e-f8d4bc8f339c.png)
