### ISSUE TITLE
5/07/20 미팅 Objectives and Discussion

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#16]
Objectives & Homework

- [x] CRUD Expression on new row https://github.com/cw-infinite/bemonster/issues/22
- [x] V0.3 UI Minor Enhancement
  - [x]  Add button
- [x] Plotly 연구 https://github.com/cw-infinite/bemonster/issues/18
- [x] Prototype 0.4 연구 
  - [x] 드롭다운 메뉴 https://github.com/cw-infinite/bemonster/issues/20
  - [x] Semantic UI 연구

**Comment by jsong0521** [comment]
물어볼 것들
- Semantic UI 개념
- 리액트의 개념

Discussion
- Reference line on a chart
- Killer feature

**Comment by cw-infinite** [comment]
mathjs introduce https://github.com/cw-infinite/bemonster/issues/7

**Comment by cw-infinite** [comment]
5/7 미팅 끝!
