### ISSUE TITLE
피카츄 모양에 대응하는 plot

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#17]
디폴트 그래프로 보여줄 피깓휴 모양

리소스:  Shapes | Python | Plotly - 

https://plotly.com/python/shapes/

**Comment by cw-infinite** [comment]
https://www.desmos.com/calculator/i2yvtbufgv

initial page pikachu functions on graphs

여기 나온 피카츄 y랑 x 레인지만 늘려서 Quadrant 1 이나 1&4에 넣어놓자

**Comment by jsong0521** [comment]
이거 어떻게찾음ㅋㅋㅋㅋㅋ

**Comment by cw-infinite** [comment]
good software engineers know how to google 😎

**Comment by jsong0521** [comment]
근데 이거는 x, y가 전부 공식에 들어있어서 생각보다 챌린징 할수도? 계속 생각해보겠음
y=(x-55)^2+(y-54)^2+-131

**Comment by jsong0521** [comment]
나는 근성으로 이걸 만들었다..

파이선 코드 쉐어하는법 알려줘. Plotly사용함

![image](https://user-images.githubusercontent.com/63434481/80931483-16742300-8d88-11ea-9471-03bb32fe1ffd.png)

**Comment by cw-infinite** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by jsong0521** [comment]
현재 앱에서는

y = 65{-26<x<-9.65}

같은 그래프는 구현이 안 되는 것으로 확인됨

**Comment by cw-infinite** [comment]
찬찬~히 한 번 그려볼까나

- -(54 - sqrt(-x^2 + 110 x - 2894))+107
- 54 - sqrt(-x^2 + 110 x - 2894)

- -(1/10 (619 - 10 sqrt(-x^2 - 102 x - 2472)))+123
- 1/10 (619 - 10 sqrt(-x^2 - 102 x - 2472))

**Comment by jsong0521** [comment]
우선 작업에 착수하기 전에.. 몇가지 concern들

우리 그래프는 <, > 등등 이퀄리티 사인을 표현할 수 없는걸로 확인됨
desmos에 올라온 공식을 그대로 사용하려면 우리 그래프 자체에 새로운 기능을 도입하거나 지원 가능한 공식으로 치환해야 할듯

또, 현재 계획은 각각의 탭에 다른 그래프기능을 지원하도록 만드는 것인데, 라인그래프에만 피카추가 있다면 그렇게 일관적으로 보이지 않을듯?
3d plot까지는 어찌어찌 피카추 그림을 넣을 수 있겠지만, bar graph부터는 현실적으로 불가능하게됨.
그러니 
1. consistency를 포기하고 라인그래프에만 피카츄 그림을 넣는다
2. 차라리 universal한 그래피카츄 로고를 만든다
이 둘중 선택해야 할 시기가 올듯..

**Comment by cw-infinite** [comment]
> 2\. 차라리 universal한 그래피카츄 로고를 만든다
>     이 둘중 선택해야 할 시기가 올듯..

아마 2번이 더 합의점이겠군
