### ISSUE TITLE
Ploty - add a slider to a line graph

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#18]
https://plotly.com/python/sliders/

**Comment by jsong0521** [comment]
https://plotly.com/~rreusser/90/chebyshev-points-for-least-squares-curve/#/

example

**Comment by cw-infinite** [comment]
Added follow up dev story for https://github.com/cw-infinite/bemonster/issues/23 after meeting  on May 7th

**Comment by jsong0521** [comment]
Need more research; moving to milestone 0.4

**Comment by cw-infinite** [comment]
5/14 meeting reviewed
