### ISSUE TITLE
Line/legend single/multiple selection

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#31]

**Comment by jsong0521** [comment]
![newplot (3)](https://user-images.githubusercontent.com/63434481/81486070-56bc2100-9220-11ea-8f63-29d39dcd9bb8.png)


우선 single selection리서치는 끝났음; 파이썬 코드 attached

[Legend Dropdown.txt](https://github.com/cw-infinite/bemonster/files/4604622/Legend.Dropdown.txt)
