### ISSUE TITLE
Secondary Y Axis

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#33]
그래프 두개의 y range가 확연히 다를 때 Secondary Y Axis를 사용하면 쉽게 비주얼라이즈 할 수 있음. 리서치해봅시다.

![image001](https://user-images.githubusercontent.com/63434481/81434684-8db50880-9134-11ea-91e0-d976126efee7.png)

**Comment by jsong0521** [comment]
reference:

https://plotly.com/python/multiple-axes/

**Comment by jsong0521** [comment]
리서치 끝남 python code attached
이건 advanced options에 들어가야 할듯?

![newplot (4)](https://user-images.githubusercontent.com/63434481/81761302-9a6c9000-9497-11ea-90bc-14c2d3a80106.png)
[secondary y axis.txt](https://github.com/cw-infinite/bemonster/files/4619288/secondary.y.axis.txt)

**Comment by cw-infinite** [comment]
5/22 미팅에서 confirm 0.6으로 이전함
