### ISSUE TITLE
Create a tooltip for supported math expressions

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#36]
Per #12

**Comment by jsong0521** [comment]
**Supported Mathematical Operations with Examples**

Basic operations
- y = 0.034x + 13 * (3/2) -4

Exponential
- y = x^3
- y = exp(x)

Radical expression
- y = sqrt(x)
- y = x^(1/2)

Logarithms
- y = log(x)

Trigonometric functions
- y = sin(x)
- y = cos(x)
- y = tan(x)

Trigonometric functions with degrees
- y = sin(45 deg) + x

Constants
e, pi, tau


Reference:https://mathjs.org/docs/reference/functions.html

**Comment by cw-infinite** [comment]
Using Modal approch
