### ISSUE TITLE
5/14일 미팅 공지

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#37]
끝낸 아이템 태그해놓고 공지해놓을꺼 써놓는 방법도 좋겟군

**Comment by cw-infinite** [comment]
Example.
https://github.com/cw-infinite/bemonster/issues/29 Range는 default 100,000 unit

**Comment by jsong0521** [comment]
#31 & #33 research complete

**Comment by jsong0521** [comment]
Revisit #29 and #38

**Comment by cw-infinite** [comment]
> Revisit #29 and #38
잘못업뎃함 https://github.com/cw-infinite/bemonster/commit/497ff17cc4908ec382b96cae8e7945c2a0d0dd72

**Comment by jsong0521** [comment]
Github - set each task's priority?

**Comment by cw-infinite** [comment]
새로운 라이브러리 color picker
https://casesandberg.github.io/react-color/

**Comment by cw-infinite** [comment]
미팅할때 같이 끝내는 걸로 https://github.com/cw-infinite/bemonster/issues/26

**Comment by cw-infinite** [comment]
5/14 meeting done!!!
