### ISSUE TITLE
Hide Y-axis range customization 

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#41]
Y-axis range를 커스터마이즈 할 수 있는 옵션을 우선은 숨겨놓읍시다

**Comment by cw-infinite** [comment]
https://github.com/cw-infinite/graphicachu/issues/49 이거 했으니까 이건 다음 버젼으로 ㅋㅋ

**Comment by cw-infinite** [comment]
https://github.com/cw-infinite/graphicachu/commit/7e6f514a3c8809f117c2ebbf32137e0fb5ecda4c done
