### ISSUE TITLE
5/21 미팅 어젠다

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#44]

**Comment by cw-infinite** [comment]
Postponed Meeting at 8PM Friday May 22nd

**Comment by jsong0521** [comment]
데이타셋을 불러올수 있는 프로그램을 생각해봐야할듯

**Comment by cw-infinite** [comment]
https://github.com/cw-infinite/graphicachu/issues/46 Feedback 부탁! @jsong0521  미팅때까지 생각해보고 알려주시길

**Comment by cw-infinite** [comment]
https://github.com/cw-infinite/graphicachu/issues/42 completed

**Comment by jsong0521** [comment]
Junhong Song is inviting you to a scheduled Zoom meeting.

Topic: 금요일 8시 미팅
Time: May 22, 2020 08:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://us04web.zoom.us/j/74263053144?pwd=cS9LRU9YbW5NRlZtY0p6b2REaHYvdz09

Meeting ID: 742 6305 3144
Password: 3xeVPB

**Comment by cw-infinite** [comment]
https://github.com/cw-infinite/graphicachu/issues/30 Revisit

**Comment by cw-infinite** [comment]
설명이 필요한 모든 부분을 적어놓는걸로
follow up issue는 나중에 만들어주시길 @jsong0521 
modal approach
- Expression
- Hex number
- 
tooltip approah
- Add button Remove button 
-

**Comment by cw-infinite** [comment]
미팅 끝ㅌㅌㅌㅌㅌㅌㅌ!!!!
