### ISSUE TITLE
Side mini Project 아이디어

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#46]
전생 집 테스트하다가 갑자기 소름이 돋앗음

우리도 혹시 심리 테스트 앱을 만들어 볼까 생각을 해봄.. 아이디어

금방 만들 수 있을꺼같음. 이걸 유툽으로 보여준애도 있고 React Native. 다음 Prototyp 1.1부터 생각해본 툴이야. 암튼.

형이 장난으로라도 할 수 있거나 (혹은 우리가 그래피카츄에 반영해서 쓸수 있는 meaningful한 )
공식을 추출해 내기에 좋은 심리 테스트를 무료로 배포 (접속자가 많을수록 광고비 효과도 생각할수 있음) 모아온 데이터로 재밌는걸 할 수 있을꺼같다는 생각이 듬.

만약 첫번쨰가 어느정도 성공했다. 성공의 기준은 (데이터 세트가 100개가 모였다 치자)
2 번째 심리테스트또한 어렵지 않겟지 텍스트만 바꾸거나 사진등만 바꾸고
처음 만든 앱에 구조를 비슷하게쓰면 심리 테스트 앱 토픽은 몇백가지라 생각함.

중요한건. 데이터가 있다면 어떠한 correlation을 만들 수 있지 않을까 ㅎㅎㅎㅎ 
걍 아이디어임

good/bad 객관적인 feedback을 부탁함. 

이 프로젝트에서 배울점이라하면
- 광고 올리기/ 혹은 이익 구조 기초
- 어플리케이션을 퍼플릭화 연습
- 형과 내가 같이 statistic으로 언제어디서든 쓸수 있는 클라우드 데이터 베이스

**Comment by jsong0521** [comment]
굉장히 쩌는 아이디어인데?

우선 나는 일하면서/대학원 다니면서 심리테스트를 수십가지 만들어봄..

심리테스트는 두가지로 나뉠수 있겠는데
1. 아무 의미없는 대중 심리테스트 (예: 짜장면 선택시 당신은 원빈 닮은 사람이라고 알려줌)
2. Mbti같은 어느정도 심리학 베이스가 있는 심리테스트 (이것도 reliable하진 않은데 그나마 과학적임)

아마 수익/재미/차별화를 위해서 우리는 위 두가지 조건을 적당히 consolidate해야겠지?

이 아이어가 쩌는 이유는.. 수익성을 떠나서 학자의 관점에서 바라보자면..

모든 심리테스트 문항은 인간의 정신적인 측면을 측정할 잠재력이 있음.
예를들어 우리가 아주 많은 데이타를 취합하고 연구를 거듭한다면 "찐따력"이라는 인간의 정신적 면모를 확립하고 그 분야의 거장이 될수 있는거임 

개인적으론 굉장히 흥미있는 프로젝트이고, 그만큼 엄청난 노력이 필요할거라 예상됨

그리고 여기서 나오는 데이타를 우리가 만든 툴로 분석이 가능하다면 그만한게 없겠지

빠른시일내로 feedback 달아주면 심리테스트 aka psychometrics 101 워크숍 준비해줌..

**Comment by jsong0521** [comment]
여기서 아이디어를 확장한다면 유저가 심리테스트를 만들수 있도록 툴을 제공하는것도 좋을듯?

**Comment by cw-infinite** [comment]
> 여기서 아이디어를 확장한다면 유저가 심리테스트를 만들수 있도록 툴을 제공하는것도 좋을듯?
이건 좀 아이디어 디벨롭을 많이해야 할듯 
1. 너무 variation 이 많아질듯 가능성이 무한해서 
2. 이건 기본기능만 생각해봐도 나혼자는 무리일꺼같음 
3. 기본기능만 만들더라도 usability면에서 쓰지 않을 가능성이 많음
