### ISSUE TITLE
철우 숙제: 첫 연습 프로그램 만들어보기

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#5]
디자인 파일과 파이썬 스크립트를 보고 User Friendly프로그램 만들어보기!

![image](https://user-images.githubusercontent.com/63434481/79171889-32a42600-7dc1-11ea-99e5-61520c336a96.png)

**Comment by jsong0521** [comment]
코드는 simple equation graphing tool 참고

**Comment by jsong0521** [comment]
레이블을 "숙제"로 했어야 하는구만!


어제 멘션했던 3D데이타적 한계에 대한 코멘트 및 솔루션:


어제 질문은 아마...

예) 1,000 x 1,000일 경우 1,000,000개의 셀을 생성해야 하는데 그정도 데이타량을 감당할 수 없을 시기가 올 수도 있다.

였을거임.

하지만 그럴 경우 굳이 백만개의 셀을 만들 필요는 없음. 인터벌을 [0,1,2,3,4...]대신 [0,10,20,30...]으로 가면 되기 때문임.

첨부된 그림파일을 보면 더 이해가 잘 될텐데,

네개의 그래프는 각각 y = x**2 +2을 인터벌 4개, 10개, 50개, 100개로 나눠서 찍은거임.

좀더 쉽게 설명하자면 인터벌 4개는 그래프를 4등분한 지점에 각각 점을 찍고 그 점을 서로 이은것이고, 인터벌 100개는 그래프를 100등분 한 후 각각의 점을 서로 이은것이지..

우리는 여기서 인터벌이 100정도만 되어도 인간의 눈으로 보기엔 충분히 스무스하다는 걸 알 수 있다능.

3d플롯의 경우에는 인터벌이 배수가 되어야 하겠지만 어떤 베리어블을 집어넣든 인터벌을 100x100으로 유지하면 비주얼적으로나 연산속도 면에서나 문제가 없을것임! 

설명이 길었는데 이해가 안 가는 부분 있으면 질문 환영데스

![range 4](https://user-images.githubusercontent.com/63434481/79251994-f1f2ee00-7e4e-11ea-9407-b8aa8236bec2.png)
![range 10](https://user-images.githubusercontent.com/63434481/79251995-f1f2ee00-7e4e-11ea-8504-81901259d8f0.png)
![range 50](https://user-images.githubusercontent.com/63434481/79251996-f28b8480-7e4e-11ea-88f9-28e550cded21.png)
![range 100](https://user-images.githubusercontent.com/63434481/79251997-f28b8480-7e4e-11ea-8908-428320e04a61.png)

**Comment by cw-infinite** [comment]
![1](https://user-images.githubusercontent.com/8744525/79627322-49ba7f00-8105-11ea-882b-252274bfb111.PNG)
1,000,000 으로 찍어봤는데 생각보다 엄청 빠름
![2](https://user-images.githubusercontent.com/8744525/79627335-6060d600-8105-11ea-8e1c-f1ae00b1301c.PNG)
10,000 x 10,000 도 이상없어서 리미트를 찍어봄
![3](https://user-images.githubusercontent.com/8744525/79627349-75d60000-8105-11ea-9a06-64ebf78558d3.PNG)
이쯤부터 그래프 rendering이 조금 느려지기 시작함
그래서 x에 대략 편안한 range는 [0, 70,000 - 80,000] 정도 인듯싶음.

**Comment by jsong0521** [comment]
plotly에 관련된 이슈: 
- y axis range를 임의로 설정할 수 있는지
- data interval을 임의로 설정할 수 있는지: 설정이 가능하다면 x와 y의 레인지가 방대해도 문제없을것

**Comment by jsong0521** [comment]
Matplotlib의 경우에는 axis와 interval을 임의로 설정 가능하기 때문에 레인지가 어떻게 늘어나든 연산속도에 문제가 안생김.

아래는 x range: 10 ^19; y range: 10 ^ 19로 그래프해본 것.

plotly가 이 문제를 해결할 수 없다면 matplotlib으로 가야할듯?

![ddd](https://user-images.githubusercontent.com/63434481/79671150-2a1f6700-8196-11ea-9cfe-1deb3a1fcbb1.png)

**Comment by cw-infinite** [comment]
React 공부하면서 디자인생각해보다가 생각난 blocker.
`Blocker : A blocker might be an issue or bug which you have come across during development or testing and which is not allowing you to develop or test further`

우리가 그냥 공식칸에다가 적는 공식은 사실 그냥 text 쪼가리라 이걸 인식하고
어떻게 컴터한테 오더할지는 구조방식을 조금 생각해야할듯 

> 아마 새로운 라이브러리를 쓸꺼임.

... 쉬울줄 알았는데 
공식에 구호나 /*-+를 제외한 다른 character들은
인식할려면 좀 **할 수 는 있지만 시간이 많이걸림**  

그래서 아마 일단은 첫번쨰 V0.1 Prototype은 정확하게 적혀진 공식으로 일단 써보고
리서치 이슈 #7 가 끝나는대로 V0.2 에서 적용시켜보겠음

**Comment by cw-infinite** [comment]
> plotly에 관련된 이슈:
> 
> * y axis range를 임의로 설정할 수 있는지
> * data interval을 임의로 설정할 수 있는지: 설정이 가능하다면 x와 y의 레인지가 방대해도 문제없을것

리미트는 아마 당분간 걱정안해도 될듯 그리고 임의설정은 전혀 문제없음 👍
