### ISSUE TITLE
fetish test 1차 미팅 정리

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#52]
결과 창
- 결과 이름
- 상세 설명
- 5가지의 subdimension 결과
- 통계
- 다른 테스터들과의 관계

문항
- 최대 20문항 최소 10문항
- 5의 배수 
- 5 point Likert Scale

기타
- 유저에게 타이틀을 줘야함
- 와 이거 완전 나잖아?
- 서로 공유하며 낄낄거림 가능

Demographic Questionnaire (추후 통계를 위해 필요함)
- 성별
- 나이

**Comment by cw-infinite** [comment]
Improvement in https://github.com/cw-infinite/graphicachu/issues/71
