### ISSUE TITLE
다음 미팅 주제 

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#6]
미팅주제 리마인더 이슈.

**Comment by jsong0521** [comment]
- 리콰이어먼트 리뷰
- 디자인 디스커션
- 깃헙 추가질문
- Contour와 3D plot 선보이기

Time: Apr 16, 2020 06:30 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://us04web.zoom.us/j/71614018544?pwd=RGMrREtWT0MxcVZOM1o2M3c2M012UT09

Meeting ID: 754 6331 8658
Password: 3Nyk2M

**Comment by cw-infinite** [comment]
Github page 를 이용한 기본적인 리액트앱
웹사이트 완성.
https://cw-infinite.github.io/bemonster/

**Comment by cw-infinite** [comment]
숙제를 줄때 서로 할일을 sub issue로 만들어놓기, 

issue page는 할일을 계속 적어놓는곳이라고 생각하면 되는데 미래에 이거를 할꺼같다 해서 계속 issue를 넣어놓고 미팅할때 수시로 review 하면 우리가 처음엔 어떻게 생각햇고 나중엔 어떻게 바꿔나가는지 트랙킹 하기 쉬움.

미팅때 할일들을 보고서 서로  assign을 해주면 좀 peer pressure도 주고 서로 뭐하는지 이해하기 더 쉬울꺼같은데 어떻게 생각하시는지?

**Comment by jsong0521** [comment]
좋은 생각인듯? 다음 미팅때 구체적으로 어떻게 할지 얘기합시다.

**Comment by cw-infinite** [comment]
4/23 미팅 주제 
@cw-infinite 
- prototype v0.1 demo
  - prototype v0,2  디자인 브레인스톰/ 리서치
  - Enhancement/Development issue 만들기 
 
- V1.0 MVP (Minimum viable product)에서 필요한 기능들 합의점보기
    - Viable&Meaningful 기능 브레인스톰/ 리서치/ 
    - Deadline/Milestone update
    - 이름후보정하기
- 깃헙 wiki 페이지 적극 활용
  - 찾은거 배운거 requirement 적극 적어놓기
  - 서로 배우고 싶은거 
  - 목표, 방향

**Comment by cw-infinite** [comment]
4/23 미팅 10-11:30
