### ISSUE TITLE
Logic Requirements 리뷰 test v0.1

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#67]
실제로 본인의 페티시 성향을 알아보자!

[logic requirement.docx](https://github.com/cw-infinite/graphicachu/files/4704872/logic.requirement.docx)

**Comment by cw-infinite** [comment]
난 마조히스트가 나왓군... 아마 그런거같기도 하고.. ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by jsong0521** [comment]
나는 나르시시스트가.. 이거 의외로 정확한데..?

**Comment by jsong0521** [comment]
재호는 가슴매니아 나옴
