### ISSUE TITLE
깃헙 레이블에 Review 추가해주삼~

### ISSUE THREAD

**Issue by jsong0521** [cw-infinite/bemonster#69]
앞으로 리절트 만들때 먼저 써놓고 리뷰 부탁하겠음!

**Comment by cw-infinite** [comment]
형도 할 수 있을껄? Label들어가서 이건 제가 먼저해놓고

다음에 생각나면 한번 연습해보시길 지울수도 있으니까 망쳐도 걱정은 마시고 ㅋㅋ
