### ISSUE TITLE
4/30/20 미팅 Objectives and Discussion

### ISSUE THREAD

**Issue by cw-infinite** [cw-infinite/bemonster#8]
**Objective**
- 이름정하고 투표해보기

**Comment by jsong0521** [comment]
**이름 리콰이어먼트**
- 직관적이어야함
- 왠지 <이름 | 설명> 이런 식이어야 할듯..? (예: Plot Machine | Visualize Your Equations)

**Comment by jsong0521** [comment]
후보..
Plotting Machine
Graphing Machine
~~Graph Visualizator~~

**Comment by cw-infinite** [comment]
후보 
~~FxPlotter~~
Graphickachu
Statistician Cafe
